#!/bin/sh /etc/rc.common
# Copyright (c) 2021 OpenWrt.org

START=80

USE_PROCD=1
PROG=/usr/sbin/ufpmd
UPDATE_OUI=/usr/share/ufpm/scripts/update-oui.uc

boot() {
	ucode "$UPDATE_OUI" || return 1
	start "$@"
}

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
