#!/bin/sh
# shellcheck shell=ash

# shellcheck source=/dev/null
. /lib/functions/system.sh
# shellcheck source=/dev/null
. /usr/share/libubox/jshn.sh

json_init

if [ -e /etc/config/wireless ]; then
	WIRELESSSTATUS="{ \"radios\": $(ubus call network.wireless status 2>/dev/null) }"
	json_load "${WIRELESSSTATUS}"
else
	# For consistency, if no wireless then return empty radio list
	json_add_object "radios"
	json_close_object
fi

# Add the basic information for the device.
json_add_string "hostname" "$(cat /proc/sys/kernel/hostname)"
json_add_string "model" "$(cat /tmp/sysinfo/model)"
json_add_string "load" "$(awk '{printf "%s %s %s", $1, $2, $3}' /proc/loadavg)"
json_add_int "uptime" "$(awk '{printf "%d", $1}' /proc/uptime)"
MAC=$(get_mac_label)
if [ -z "${MAC}" ]; then
	grep -q br-lan /proc/net/dev && IF=br-lan || IF=eth0
	MAC=$([ -e /sys/class/net/"$IF"/address ] && cat /sys/class/net/"$IF"/address || echo "")
fi
json_add_string "mac" "${MAC}"
json_add_string "software" "$(awk -F= '/^OPENWRT_RELEASE=/ {print $2}' /etc/os-release 2>/dev/null | xargs)"

# enter the radios
json_select "radios"

# for every radio
json_get_keys "radios"
# Radios set in json_get_keys call
# shellcheck disable=SC2154
for radio in ${radios}; do
	# select radioX > interfaces
	json_select "${radio}"
	json_select "interfaces"

	# iterate through the interfaces
	idx=1 # note that array element position starts from 1 not, 0
	while json_is_a "$idx" object; do
		# select interfaceX
		json_select "$idx"

		# get the interface name
		json_get_var ifname ifname

		# select config to remove key and leave
		json_select "config"
		json_add_string "key" "<removed>"
		json_select ..

		# TODO: populate iwinfo for each interface for things like signal and radio name
		json_set_namespace iwinfo finaljson
		json_init
		IWINFO=$(ubus call iwinfo info "{ \"device\": \"${ifname}\" }")
		json_load "${IWINFO}"
		
		json_get_var _ssid ssid
		json_get_var _bssid bssid
		json_get_var _channel channel
		json_get_var _center_chan1 center_chan1
		json_get_var _frequency frequency
		json_get_var _frequency_offset frequency_offset
		json_get_var _txpower txpower
		json_get_var _txpower_offset txpower_offset
		json_get_var _quality quality
		json_get_var _quality_max quality_max
		json_get_var _signal signal
		json_get_var _noise noise
		json_get_var _bitrate bitrate
		json_get_var _hwmodes_text hwmodes_text

		json_select hardware
		json_get_var _hardware_name name
		json_select ..

		json_set_namespace "$finaljson"
		json_add_object "iwinfo"
		json_add_string ssid "$_ssid"
		json_add_string bssid "$_bssid"
		json_add_int channel "$_channel"
		json_add_int center_chan1 "$_center_chan1"
		json_add_int frequency "$_frequency"
		json_add_int frequency_offset "$_frequency_offset"
		json_add_int txpower "$_txpower"
		json_add_int txpower_offset "$_txpower_offset"
		json_add_int quality "$_quality"
		json_add_int quality_max "$_quality_max"
		json_add_int signal "$_signal"
		json_add_int noise "$_noise"
		json_add_int bitrate "$_bitrate"
		json_add_string hwmodes_text "$_hwmodes_text"
		json_add_string "hardware_name" "$_hardware_name"
		
		json_close_object
	
		# select stations to insert
		json_select "stations"

		for STATION in $(iw dev "$ifname" station dump 2>/dev/null | awk '{if($1 == "Station") {MAC=$2; station[MAC]=1} if($0 ~ /rx bytes:/) {rx[MAC]=$3} if($0 ~ /tx bytes:/) {tx[MAC]=$3} if($0 ~ /^\s*signal:/) {signal[MAC]=$2} if($0 ~ /connected time:/) {connected[MAC]=$3}} END {for (s in station) {printf "%s,%s,%s,%d,%d ", s, rx[s], tx[s], signal[s], connected[s]}}'); do
			_MAC=$(echo "$STATION" | cut -d',' -f1)
			_TX=$(echo "$STATION" | cut -d',' -f2)
			_RX=$(echo "$STATION" | cut -d',' -f3)
			_SIGNAL=$(echo "$STATION" | cut -d',' -f4)
			_CONNECTED=$(echo "$STATION" | cut -d',' -f5)
			
			# start station
			json_add_object

			# station attributes
			json_add_string "mac" "$_MAC"
			json_add_int "tx" "$_TX"
			json_add_int "rx" "$_RX"
			json_add_int "signal" "$_SIGNAL"
			json_add_int "connected" "$_CONNECTED"

			# wifi mode
			T="0"
			grep -qi "^ht supported" /sys/kernel/debug/ieee80211/*/*/stations/"${_MAC}"/ht_capa 2>/dev/null && T="4"
			grep -qi "^vht supported" /sys/kernel/debug/ieee80211/*/*/stations/"${_MAC}"/vht_capa 2>/dev/null && T="5"
			grep -qi "^he supported" /sys/kernel/debug/ieee80211/*/*/stations/"${_MAC}"/he_capa 2>/dev/null && T="6"
			grep -qi "^eht supported" /sys/kernel/debug/ieee80211/*/*/stations/"${_MAC}"/eht_capa 2>/dev/null && T="7"
			json_add_int "wifi" "$T"

			# end station
			json_close_object
		done

		# leave stations
		json_select ..

		# increment index
		idx=$(( idx + 1 ))

		# leave interface
		json_select ..
	done

	# leave radioX > interfaces
	json_select ..
	json_select ..
done

# leave radios
json_select ..

json_dump

exit 0
